'use client';

import type { ContentProposalRecord } from '@/types';
import Button from '@/components/ui/Button';

const STATUS_STYLES: Record<string, string> = {
  pending: 'bg-neon-cyan/20 text-neon-cyan border-neon-cyan/40',
  approved: 'bg-emerald-500/20 text-emerald-300 border-emerald-400/40',
  rejected: 'bg-neon-pink/20 text-neon-pink border-neon-pink/40',
};

export default function ProposalCard({
  proposal,
  reviewing,
  generating,
  onApprove,
  onReject,
  onRegenerate,
}: {
  proposal: ContentProposalRecord;
  reviewing: boolean;
  generating: boolean;
  onApprove: () => void;
  onReject: () => void;
  onRegenerate: (instructions?: string) => void;
}) {
  const busy = reviewing || generating;

  return (
    <div className="glass-card rounded-2xl overflow-hidden">
      <div className="flex items-center justify-between gap-3 px-5 py-4 border-b border-glass-border bg-black/20">
        <div className="flex items-center gap-3 min-w-0">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-neon-violet to-neon-cyan flex items-center justify-center text-white font-bold text-sm flex-shrink-0">
            {proposal.fileId.slice(0, 2).toUpperCase()}
          </div>
          <div className="min-w-0">
            <h4 className="font-medium text-on-surface truncate">{proposal.file?.name || 'Media item'}</h4>
            <p className="text-xs text-text-muted truncate">{proposal.angle}</p>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          {proposal.generationSource === 'fallback' && (
            <span className="text-[10px] uppercase tracking-widest px-2 py-0.5 rounded-full border border-amber-400/40 bg-amber-400/10 text-amber-300">
              fallback
            </span>
          )}
          <span
            className={`text-label-sm px-2.5 py-0.5 rounded-full border capitalize ${STATUS_STYLES[proposal.status] || ''}`}
          >
            {proposal.status}
          </span>
        </div>
      </div>

      <div className="p-5 space-y-4">
        {proposal.previewText && (
          <p className="text-sm text-text-muted border-l-2 border-neon-cyan/50 pl-3">
            {proposal.previewText}
          </p>
        )}

        <div>
          <label className="block text-label-sm text-neon-violet uppercase tracking-widest mb-1">
            Caption
          </label>
          <p className="text-sm text-on-surface whitespace-pre-wrap bg-black/30 rounded-xl px-4 py-3">
            {proposal.caption}
          </p>
        </div>

        <div>
          <label className="block text-label-sm text-neon-violet uppercase tracking-widest mb-1">
            Post Write-up
          </label>
          <p className="text-sm text-on-surface whitespace-pre-wrap bg-black/30 rounded-xl px-4 py-3 leading-relaxed">
            {proposal.writeUp}
          </p>
        </div>

        {proposal.hashtags.length > 0 && (
          <div>
            <label className="block text-label-sm text-neon-violet uppercase tracking-widest mb-1">
              Hashtags
            </label>
            <div className="flex flex-wrap gap-1.5">
              {proposal.hashtags.map((tag) => (
                <span
                  key={tag}
                  className="text-xs glass-card px-2.5 py-1 rounded-full text-neon-cyan"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>
        )}

        <p className="text-[10px] text-text-muted/60">
          Generated by {proposal.modelUsed || 'agent'} &middot; {new Date(proposal.updatedAt).toLocaleString()}
        </p>

        {proposal.feedback && (
          <div className="text-xs text-neon-pink bg-neon-pink/10 border border-neon-pink/30 rounded-xl px-3 py-2">
            Rejection feedback: {proposal.feedback}
          </div>
        )}

        {proposal.status !== 'pending' && (
          <div className="flex items-center justify-between border-t border-glass-border pt-4">
            <p className="text-xs text-text-muted">
              {proposal.status === 'approved'
                ? 'Approved — agent content is ready to publish.'
                : 'Rejected — regenerate a new draft or leave as is.'}
            </p>
            {proposal.status === 'rejected' && (
              <Button variant="ghost" size="sm" onClick={() => onRegenerate()}>
                Regenerate
              </Button>
            )}
          </div>
        )}

        {proposal.status === 'pending' && (
          <div className="flex items-center justify-end gap-2 border-t border-glass-border pt-4">
            <Button variant="ghost" size="sm" onClick={() => onRegenerate()} disabled={busy}>
              Regenerate
            </Button>
            <Button variant="danger" size="sm" onClick={onReject} disabled={busy} loading={reviewing}>
              Reject
            </Button>
            <Button variant="primary" size="sm" onClick={onApprove} disabled={busy} loading={reviewing}>
              Approve
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}